### ISSUE TITLE
Creating server in NodeJS

### ISSUE THREAD

**Issue by underager** [learning-zone/nodejs-interview-questions#35]
## Creating server in NodeJS.
FileName : [ReadMe](https://github.com/learning-zone/nodejs-interview-questions#readme).
Question no. 5: [How to create a simple server in Node.js that returns Hello World?](https://github.com/learning-zone/nodejs-interview-questions#q-how-to-create-a-simple-server-in-nodejs-that-returns-hello-world)

Issue: The solution describes, how to create a server using express, instead of showing how to do so without express using Node.

I would like to submit a pull request to show how to create the server using http module and not express.

**Comment by learning-zone** [comment]
The `express()` is most common package used for accesing http module and I feel, there is no need to implement the same without express. It will be great, if you could add answers for remaining questions.
Thanks
